url: "https://www.example.com" # site to be monitored
check period: 15 # minutes; wait this long between looking for changes
access retry period: 5 # minutes; if site can't be reached, wait this long before trying again
notification retry period: 5 # minutes; if notification can't be sent, wait this long before trying again

# email notification settings
email subject: "Change detected" 
email message: "Change detected" 
email recipents:
  - "abc@def.ghi"

sender email: "example@gmail.com" # currently gmail only
sender password: 

# setting to true will enable verbose logging messages
debugging logs: true 